# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pp < Formula
  desc "Universal pipe pretty-printer. Auto-detects format, adds color."
  homepage "https://github.com/pakhomovld/pp"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pakhomovld/pp/releases/download/v0.2.1/ppp_darwin_amd64.tar.gz"
      sha256 "5a652a8804a95be62d8e62d2d78bb8f7d067ee8600d3f136fa986a73663f3176"

      define_method(:install) do
        bin.install "ppp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pakhomovld/pp/releases/download/v0.2.1/ppp_darwin_arm64.tar.gz"
      sha256 "170c8e3f90cdab830bbe1fbd2d07f1fdecbbbd32518e3113aa4ce544a8d93d80"

      define_method(:install) do
        bin.install "ppp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pakhomovld/pp/releases/download/v0.2.1/ppp_linux_amd64.tar.gz"
      sha256 "54775c960891cb06bde629b285ba25a1344855b6f199b6376cc377bcd87d5aa8"
      define_method(:install) do
        bin.install "ppp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pakhomovld/pp/releases/download/v0.2.1/ppp_linux_arm64.tar.gz"
      sha256 "caa2960da7230ba03fe07cc6f60da00b5bf83e8e20a102a8cfe4ecc1a83d614d"
      define_method(:install) do
        bin.install "ppp"
      end
    end
  end

  test do
    assert_match "ppp version", shell_output("#{bin}/ppp --version")
  end
end
