# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ppp < Formula
  desc "Universal pipe pretty-printer. Auto-detects format, adds color."
  homepage "https://github.com/pakhomovld/ppp"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pakhomovld/ppp/releases/download/v0.3.0/ppp_darwin_amd64.tar.gz"
      sha256 "b30bb7506f2a6d8f31c99d6e4ea033b3a6241747ae515d73f69fdc228ddffda5"

      define_method(:install) do
        bin.install "ppp"
        man1.install "ppp.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pakhomovld/ppp/releases/download/v0.3.0/ppp_darwin_arm64.tar.gz"
      sha256 "b5bfe68e18732a046a9338687e0bf5db56511b57c5db9a2bafd302c8e0188798"

      define_method(:install) do
        bin.install "ppp"
        man1.install "ppp.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pakhomovld/ppp/releases/download/v0.3.0/ppp_linux_amd64.tar.gz"
      sha256 "1ca0df7acf1c79cfcd3073c69ad0bffcb8cb9162d0e3a528a2815cac5fe4413d"
      define_method(:install) do
        bin.install "ppp"
        man1.install "ppp.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pakhomovld/ppp/releases/download/v0.3.0/ppp_linux_arm64.tar.gz"
      sha256 "ac9e24e490e8bcc6252f430453629d08adc846ea945acaadc156a99996789c51"
      define_method(:install) do
        bin.install "ppp"
        man1.install "ppp.1"
      end
    end
  end

  test do
    assert_match "ppp version", shell_output("#{bin}/ppp --version")
  end
end
