# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ppp < Formula
  desc "Universal pipe pretty-printer. Auto-detects format, adds color."
  homepage "https://github.com/pakhomovld/ppp"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pakhomovld/ppp/releases/download/v0.3.1/ppp_darwin_amd64.tar.gz"
      sha256 "a1bbbb5e0c3288a901e156ff981c6dff7ca984538e8b032ec300a71bd2b2f6f2"

      define_method(:install) do
        bin.install "ppp"
        man1.install "ppp.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pakhomovld/ppp/releases/download/v0.3.1/ppp_darwin_arm64.tar.gz"
      sha256 "549d5dc813919bd233456e2a372ef2dbc748d74c6254f6a9e8952eae01a80ce7"

      define_method(:install) do
        bin.install "ppp"
        man1.install "ppp.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pakhomovld/ppp/releases/download/v0.3.1/ppp_linux_amd64.tar.gz"
      sha256 "92462788794bd04f6e21239d17cc4c3716734eb38255aa3d52d3fb0bad6617bc"
      define_method(:install) do
        bin.install "ppp"
        man1.install "ppp.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pakhomovld/ppp/releases/download/v0.3.1/ppp_linux_arm64.tar.gz"
      sha256 "752788f56075061d83c098226521bb4c44f31758ec1c7195ea9da3afeb8ba430"
      define_method(:install) do
        bin.install "ppp"
        man1.install "ppp.1"
      end
    end
  end

  test do
    assert_match "ppp version", shell_output("#{bin}/ppp --version")
  end
end
